//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correspondence
    {
        public int id_Correspondence { get; set; }
        public int id_Subscribe { get; set; }
        public string DeliveryAddres { get; set; }
        public System.DateTime DateOfDispatch { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
    
        public virtual Subscribe Subscribe { get; set; }
    }
}
