//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIO
    {
        public int id_Journal { get; set; }
        public int id_User { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
